# Generated by Django 5.0.4 on 2024-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("time_requested", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_error_flag", models.BooleanField(default=False)),
                ("consensus_error_flag", models.BooleanField(default=False)),
                ("responses", models.ManyToManyField(to="api.response")),
            ],
        ),
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rubric_component", models.TextField()),
                ("student_response", models.TextField()),
                ("context", models.TextField(blank=True, null=True)),
                ("flagged", models.BooleanField(default=False)),
                ("rounds", models.ManyToManyField(to="api.round")),
            ],
        ),
    ]
